In [1]:
import pandas as pd

## Q1. Pandas version

In [3]:
pd.__version__

'2.3.1'

## Getting the data

In [5]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2025-10-01 18:54:00--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv’

car_fuel_efficiency 100%[===================>] 853.70K  --.-KB/s    in 0.005s  

2025-10-01 18:54:00 (175 MB/s) - ‘car_fuel_efficiency.csv’ saved [874188/874188]



In [7]:
df = pd.read_csv("car_fuel_efficiency.csv", header=0)

In [8]:
df.head

<bound method NDFrame.head of       engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Eu

## Q2. Records count

In [9]:
df.shape[0]

9704

## Q3. Fuel types

In [13]:
df.fuel_type.describe()

count         9704
unique           2
top       Gasoline
freq          4898
Name: fuel_type, dtype: object

## Q4. Missing values

In [14]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

## Q5. Max fuel efficiency

In [15]:
df.origin.fuel_efficiency_mpg.max()

np.float64(25.96722204888372)

In [23]:
df[
    df['origin'] == 'Asia'
].fuel_efficiency_mpg.max()

np.float64(23.759122836520497)

## Q6. Median value of horsepower

In [24]:
df.horsepower.median()

np.float64(149.0)

In [27]:
horsepower_mode = df.horsepower.mode()
horsepower_mode

0    152.0
Name: horsepower, dtype: float64

In [28]:
df.horsepower = df.horsepower.fillna(horsepower_mode)

In [29]:
df.horsepower.median()

np.float64(149.0)

Yes, it decreased.

## Q7. Sum of weights

In [66]:
X = df[['vehicle_weight', 'model_year']][
    df['origin'] == 'Asia'
].iloc[:7].to_numpy()

X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [67]:
X.T

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [68]:
XTX = X.T.dot(X)

XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [69]:
import numpy as np 

XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [70]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [71]:
w1 = XTX_inv.dot(X.T)

w = w1.dot(y)

w

array([0.01386421, 0.5049067 ])

In [72]:
np.sum(w)

np.float64(0.5187709081074016)